# Generated by Django 3.2 on 2021-04-11 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('writer', models.CharField(max_length=225)),
                ('thumbnail1', models.ImageField(default='default.jpg', upload_to='thumbnail')),
                ('thumbnail2', models.ImageField(default='default.jpg', upload_to='thumbnail')),
                ('cost_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('mobile_no', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('educational_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='commerce.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
