# Generated by Django 3.2 on 2021-04-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.CharField(max_length=10),
        ),
    ]
